import type { RichTextEditorLabels } from '@mantine/tiptap'

const translatedLabels: Partial<RichTextEditorLabels> = {
  alignCenterControlLabel: 'Zentriert',
  alignJustifyControlLabel: 'Blocksatz',
  alignLeftControlLabel: 'Linksbündig',
  alignRightControlLabel: 'Rechtsbündig',
  blockquoteControlLabel: 'Blockzitat',
  boldControlLabel: 'Fett',
  italicControlLabel: 'Kursiv',
  underlineControlLabel: 'Unterstrichen',
  strikeControlLabel: 'Durchgestrichen',
  clearFormattingControlLabel: 'Formatierung entfernen',
  linkControlLabel: 'Link einfügen',
  unlinkControlLabel: 'Link entfernen',
  bulletListControlLabel: 'Liste',
  orderedListControlLabel: 'Nummerierte Liste',
  h1ControlLabel: 'Überschrift 1',
  h2ControlLabel: 'Überschrift 2',
  h3ControlLabel: 'Überschrift 3',
  h4ControlLabel: 'Überschrift 4',
  h5ControlLabel: 'Überschrift 5',
  h6ControlLabel: 'Überschrift 6',
  codeControlLabel: 'Code',
  codeBlockControlLabel: 'Codeblock',
  subscriptControlLabel: 'Tiefgestellt',
  superscriptControlLabel: 'Hochgestellt',
  colorPickerControlLabel: 'Textfarbe auswählen',
  unsetColorControlLabel: 'Textfarbe entfernen',
  highlightControlLabel: 'Hervorheben',
  undoControlLabel: 'Rückgängig',
  redoControlLabel: 'Wiederholen',
  sourceCodeControlLabel: 'Quellcode anzeigen',
  linkEditorInputLabel: 'URL',
  linkEditorInputPlaceholder: 'https://beispiel.de',
  linkEditorExternalLink: 'In neuem Tab öffnen',
  linkEditorInternalLink: 'Im selben Tab öffnen',
  linkEditorSave: 'Speichern',
  colorPickerCancel: 'Abbrechen',
  colorPickerClear: 'Leeren',
  colorPickerColorPicker: 'Farbe auswählen',
  colorPickerPalette: 'Farbpalette',
  colorPickerSave: 'Speichern',
  tasksControlLabel: 'Aufgabenliste',
  tasksSinkLabel: 'Aufgabe einrücken',
  tasksLiftLabel: 'Aufgabe ausrücken',
  hrControlLabel: 'Linie',
  colorControlLabel: (color: string) => `Farbe ${color}`,
  colorPickerColorLabel: (color: string) => `Farbe ${color}`,
}

export default translatedLabels
